import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sawarabi_Gothic } from "next/font/google";
import SessionWrapper from "../components/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sawarabiGothic = Sawarabi_Gothic({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-sawarabi-gothic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sawarabiGothic.variable} antialiased bg-black`}
      >
        <SessionWrapper>{children}</SessionWrapper>
      </body>
    </html>
  );
}
